# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 16:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('connection_type', models.CharField(choices=[(b'MODBUS', b'ModBus Connection')], max_length=31)),
                ('connection_info', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.IntegerField()),
                ('lng', models.IntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('unit_type', models.CharField(choices=[(b'GENERIC_BUILDING', b'Building'), (b'FACTORY', b'Factory'), (b'CHARGING_STATION', b'Charging station')], max_length=31)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='region',
            name='parent_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.Unit'),
        ),
    ]
