# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 09:45
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='info',
            field=jsonfield.fields.JSONField(default={}),
        ),
    ]
