# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_unit_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='location',
        ),
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='lat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='lng',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
