# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0003_auto_20160309_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unit',
            name='lng',
            field=models.FloatField(),
        ),
    ]
