# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_auto_20160309_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='parent_region',
        ),
        migrations.RemoveField(
            model_name='region',
            name='parent_unit',
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
